// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    'Carbon:logoTwitter': typeof import('~icons/carbon/logo-twitter')['default']
    FeatherTwitter: typeof import('~icons/feather/twitter')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LaRssSquare: typeof import('~icons/la/rss-square')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    RiArticleLine: typeof import('~icons/ri/article-line')['default']
    RiBookmarkLine: typeof import('~icons/ri/bookmark-line')['default']
    RiMoonLine: typeof import('~icons/ri/moon-line')['default']
    RiSunLine: typeof import('~icons/ri/sun-line')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    Transform: typeof import('./src/components/Transform.vue')['default']
    Tweet: typeof import('./src/components/Tweet.vue')['default']
    UilGithubAlt: typeof import('~icons/uil/github-alt')['default']
  }
}

export { }
