import {
  defineConfig,
  extractorDefault,
  presetAttributify,
  presetWind4,
  transformerVariantGroup,
} from 'unocss'
import { presetIcons } from '@unocss/preset-icons'

export default defineConfig({
  presets: [
    presetWind4({ preflights: { reset: true } }),
    presetAttributify({ strict: true }),
    presetIcons({ scale: 1.2, warn: true }),
  ],
  // Strict attributify disables script extraction, including useHead and transition classes.
  extractorDefault,
  theme: {
    colors: {
      canvas: { light: '#ffffff', dark: '#0d0d0d' },
      code: { light: '#f7f7f7', dark: '#171717' },
      panel: { light: '#f0f0f0', dark: '#1c1c1c' },
      hover: { light: '#f4f4f4', dark: '#1c1c1c' },
      line: { light: '#e7e7e7', dark: '#2b2b2b' },
      body: { light: '#373737', dark: '#bcbcbc' },
      muted: { light: '#686868', dark: '#949494' },
      heading: { light: '#202020', dark: '#ededed' },
      accent: { light: '#287858', dark: '#83c5a0' },
      highlight: { light: '#28785812', dark: '#83c5a016' },
      selection: '#83c5a044',
      overlay: '#10101088',
    },
    font: {
      sans: '"Inter", Inter var,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji',
      mono: '"Fira Code", ui-monospace, monospace',
    },
  },
  transformers: [transformerVariantGroup()],
  shortcuts: {
    'canvas-surface': 'bg-canvas-light dark:bg-canvas-dark',
    'code-surface': 'bg-code-light dark:bg-code-dark',
    'panel-surface': 'bg-panel-light dark:bg-panel-dark',
    'interactive-surface': 'bg-hover-light dark:bg-hover-dark',
    'line-color': 'border-line-light dark:border-line-dark',
    'body-color': 'text-body-light dark:text-body-dark',
    'heading-color': 'text-heading-light dark:text-heading-dark',
    'muted': 'text-muted-light dark:text-muted-dark',
    'accent': 'text-accent-light dark:text-accent-dark',
    'text-link': 'accent',
    'site-root': 'min-h-100dvh text-16px font-sans antialiased scheme-light [&.dark]:scheme-dark [scrollbar-width:thin] [scrollbar-color:#cfcfcf_transparent] [&.dark]:[scrollbar-color:#373737_transparent]',
    'nuxt-root': 'min-h-100dvh canvas-surface',
    'site-body': 'min-h-100dvh m-0 canvas-surface body-color [&>#\\_\\_nuxt]:nuxt-root scheme-light dark:scheme-dark selection:bg-selection [&_button]:cursor-pointer [&_:where(:focus-visible)]:outline-2 [&_:where(:focus-visible)]:outline-solid [&_:where(:focus-visible)]:outline-accent-light dark:[&_:where(:focus-visible)]:outline-accent-dark [&_:where(:focus-visible)]:outline-offset-5 [&_:where(:focus-visible)]:rounded-2px [scrollbar-width:thin] [&_*]:[scrollbar-width:thin] [&_*]:[scrollbar-color:#cfcfcf_transparent] dark:[&_*]:[scrollbar-color:#373737_transparent] motion-reduce:[&_*]:!scroll-auto motion-reduce:[&_*]:!transition-none motion-reduce:[&_*]:!animate-none motion-reduce:[&_*::before]:!scroll-auto motion-reduce:[&_*::before]:!transition-none motion-reduce:[&_*::before]:!animate-none motion-reduce:[&_*::after]:!scroll-auto motion-reduce:[&_*::after]:!transition-none motion-reduce:[&_*::after]:!animate-none',
    'site-shell': 'w-[min(calc(100%-3rem),44rem)] mx-auto [@media(max-width:560px)]:w-[calc(100%-2.5rem)]',
    'site-header': 'flex items-center gap-8 pt-14 pb-20 [@media(max-width:560px)]:gap-4 [@media(max-width:560px)]:pt-8 [@media(max-width:560px)]:pb-14 [@media(max-width:560px)]:flex-wrap',
    'wordmark': 'text-2rem font-600 tracking-[-.1em] heading-color leading-[1]',
    'site-nav': 'flex gap-6 text-[.875rem] [@media(max-width:560px)]:gap-4',
    'nav-link': 'muted py-[.65rem] hover:accent [&[aria-current]]:accent',
    'site-tools': 'flex items-center gap-1 ml-auto [@media(max-width:560px)]:w-full [@media(max-width:560px)]:ml-[-.6rem]',
    'tool-button': 'inline-flex justify-center items-center size-10 muted rounded-[.35rem] shrink-0 hover:accent hover:interactive-surface',
    'skip-link': 'fixed top-3 left-3 py-[.65rem] px-4 canvas-surface accent z-100 translate-y-[-200%] focus:translate-y-0',
    'page-content': 'text-[1rem] leading-[1.85] [overflow-wrap:anywhere] [&_:where(img,video)]:max-w-full [&_:where(img,video)]:h-auto [&_:not(pre)>code]:inline-code',
    'page-heading': 'mb-10',
    'page-title-row': 'flex items-center flex-wrap gap-4 mt-[.6rem] mb-6',
    'page-title': 'text-[clamp(1.85rem,4vw,2.4rem)] leading-[1.35] font-600 tracking-[-.035em] heading-color',
    'page-date': 'font-mono text-[.75rem] muted',
    'about-heading': 'flex items-center gap-5 mb-11',
    'avatar': 'block shrink-0 size-18 rounded-full overflow-hidden [&_img]:size-full [&_img]:object-cover [@media(max-width:560px)]:size-14',
    'post-year': 'mb-12',
    'post-row': 'flex items-start gap-5 leading-[1.6] [@media(max-width:560px)]:gap-[.85rem]',
    'post-thumbnail': 'block w-28 h-18 shrink-0 overflow-hidden rounded-[.35rem] interactive-surface border line-color [&_img]:block [&_img]:size-full [&_img]:object-cover [@media(max-width:560px)]:w-20 [@media(max-width:560px)]:h-13',
    'post-row-content': 'flex-1 min-w-0',
    'post-row-heading': 'flex items-baseline justify-between gap-6 [@media(max-width:560px)]:flex-col [@media(max-width:560px)]:gap-[.2rem]',
    'post-row-title': 'heading-color transition-colors duration-150 group-hover:text-accent-light dark:group-hover:text-accent-dark',
    'post-time': 'text-[.7rem] font-mono muted shrink-0',
    'post-description': 'muted text-[.875rem] leading-[1.7] mt-[.35rem]',
    'site-footer': 'pt-12 pb-10 mt-12 border-t line-color muted text-[.75rem] leading-[1.8] [&_a:hover]:accent',
    'footer-links': 'flex gap-5 mb-[.7rem]',
    'dialog-overlay': 'fixed inset-0 bg-overlay z-50',
    'site-dialog': 'fixed top-[min(15vh,7rem)] left-1/2 -translate-x-1/2 w-[min(calc(100%-2rem),36rem)] max-h-75dvh overflow-y-auto p-6 canvas-surface border line-color rounded-[.65rem] shadow-[0_1rem_4rem_#0003] z-51 [@media(max-width:560px)]:p-5',
    'dialog-heading': 'flex justify-between items-center heading-color font-600 text-[1.125rem]',
    'dialog-description': 'muted text-[.875rem] leading-[1.65] mt-2 mb-5',
    'search-input': 'w-full py-3 px-4 interactive-surface border line-color rounded-[.35rem] heading-color placeholder:muted',
    'search-status': 'text-[.75rem] muted mt-5 mb-2',
    'search-result': 'flex items-baseline justify-between gap-4 py-[.8rem] px-2 text-[.875rem] leading-[1.65] border-b line-color hover:accent hover:interactive-surface [@media(max-width:560px)]:flex-col [@media(max-width:560px)]:gap-1',
    'shortcut-row': 'flex justify-between items-center py-[.65rem] border-b line-color text-[.875rem]',
    'shortcut-key': 'inline-block font-mono text-[.75rem] leading-[1.4] muted border line-color rounded py-[.2rem] px-[.4rem] min-w-[1.65rem] text-center',
    'shortcut-setting': 'flex items-center gap-[.6rem] mt-5 text-[.75rem] muted',
    'dialog-note': 'text-[.75rem] muted mt-5',
    'code-panel': 'my-6 border line-color rounded-lg overflow-hidden code-surface',
    'code-header': 'flex items-center gap-3 py-[.6rem] px-4 border-b line-color panel-surface text-[.75rem] leading-[1.5] [@media(max-width:560px)]:gap-2 [@media(max-width:560px)]:px-3',
    'code-label': 'min-w-0 [overflow-wrap:anywhere] font-mono heading-color',
    'code-language': 'muted',
    'code-copy': 'inline-flex items-center gap-[.4rem] py-[.35rem] px-2 ml-auto shrink-0 muted rounded hover:accent hover:canvas-surface disabled:cursor-wait disabled:opacity-60 [@media(max-width:560px)]:min-h-11',
    'code-body': 'max-w-full overflow-x-auto m-0 py-4 code-surface font-mono text-[.8125rem] leading-[1.8] whitespace-pre [overflow-wrap:normal] [tab-size:2] focus-visible:outline-offset-[-3px] focus-visible:rounded-none [&>code]:block [&>code]:w-max [&>code]:min-w-full [&>code]:[font:inherit] [&_.line]:block [&_.line]:min-h-[1.8em] [&_.line]:px-5 [@media(max-width:560px)]:[&_.line]:px-4 [&_.line.highlight]:bg-highlight-light dark:[&_.line.highlight]:bg-highlight-dark [&_.line.highlight]:shadow-[inset_2px_0_theme(colors.accent.light)] dark:[&_.line.highlight]:shadow-[inset_2px_0_theme(colors.accent.dark)]',
    'code-error': 'm-0 py-[.65rem] px-4 border-t line-color body-color text-[.8125rem] leading-[1.6]',
    'inline-code': 'py-[.15em] px-[.35em] border line-color rounded code-surface font-mono text-[.875em] box-decoration-clone',
    'prose-link': 'accent underline decoration-line-light dark:decoration-line-dark underline-offset-[.2em] hover:decoration-accent-light dark:hover:decoration-accent-dark',
    'icon-link': 'block muted hover:accent',
    'tooltip-panel': 'z-50 rounded panel-surface heading-color border line-color px-2 py-1 text-[.75rem] shadow',
  },
})
