// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    'Carbon:checkmark': typeof import('~icons/carbon/checkmark')['default']
    'Carbon:link': typeof import('~icons/carbon/link')['default']
    'Carbon:logoFacebook': typeof import('~icons/carbon/logo-facebook')['default']
    'Carbon:logoTwitter': typeof import('~icons/carbon/logo-twitter')['default']
    FeatherTwitter: typeof import('~icons/feather/twitter')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    'Ic:roundMail': typeof import('~icons/ic/round-mail')['default']
    'IconParkOutline:closeSmall': typeof import('~icons/icon-park-outline/close-small')['default']
    LaRssSquare: typeof import('~icons/la/rss-square')['default']
    ListPosts: typeof import('./components/ListPosts.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    RiArticleLine: typeof import('~icons/ri/article-line')['default']
    RiBookmarkLine: typeof import('~icons/ri/bookmark-line')['default']
    RiMoonLine: typeof import('~icons/ri/moon-line')['default']
    RiSunLine: typeof import('~icons/ri/sun-line')['default']
    ShareButtons: typeof import('./components/ShareButtons.vue')['default']
    TagLabel: typeof import('./components/TagLabel.vue')['default']
    TagSelectList: typeof import('./components/TagSelectList.vue')['default']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
    Transform: typeof import('./components/Transform.vue')['default']
    Tweet: typeof import('./components/Tweet.vue')['default']
    'Uil:line': typeof import('~icons/uil/line')['default']
    UilGithubAlt: typeof import('~icons/uil/github-alt')['default']
  }
}

export { }
