// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ListPosts: typeof import('./components/ListPosts.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButtons: typeof import('./components/ShareButtons.vue')['default']
    TagLabel: typeof import('./components/TagLabel.vue')['default']
    TagSelectList: typeof import('./components/TagSelectList.vue')['default']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
    Transform: typeof import('./components/Transform.vue')['default']
    Tweet: typeof import('./components/Tweet.vue')['default']
  }
}
